baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
enableRobotsTXT = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowingShareButtons = true
    ShowPostNavLinks = true

    homeInfoParams.Title = "Welcome"
    homeInfoParams.Content = "Engineering, Labs, and Reflections."

    [menu]
      [[menu.main]]
        identifier = "engineering"
        name = "Engineering"
        url = "/engineering/"
        weight = 10
      [[menu.main]]
        identifier = "lab"
        name = "Lab"
        url = "/lab/"
        weight = 20
      [[menu.main]]
        identifier = "reflections"
        name = "Reflections"
        url = "/reflections/"
        weight = 30
      [[menu.main]]
        identifier = "search"
        name = "Search"
        url = "/search/"
        weight = 40

[frontmatter]
    lastmod = [":git", "lastmod", "date"]
